# Generated by Django 5.0.5 on 2024-05-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_order_order_items_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
